apiVersion: v1
kind: Secret
metadata:
  name: scheduler-secrets
type: Opaque
stringData:
  TOOL_PAYLOADS_BUCKET: "{{ .Values.toolPayloadsBucket }}"
  LANGFUSE_PUBLIC_KEY: "{{ .Values.langfusePublicKey }}"
  LANGFUSE_SECRET_KEY: "{{ .Values.langfuseSecretKey }}"
